apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: dbb
  description: DBB
spec:
  owner: eu-b2b
  
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: eu-b2b
  description: EU B2B
spec:
  type: business-unit
  profile:
    displayName: EU B2B
    email: eu-b2b@example.com
    picture: https://cdn-icons-png.flaticon.com/512/2037/2037737.png
  children: [sre, m2c, epc]

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: sre
  description: Site Reliability Engineering.
spec:
  type: business-unit
  profile:
    displayName: Site Reliability Engineering
    email: sre@example.com
    picture: https://cdn-icons-png.flaticon.com/512/2037/2037737.png
  parent: eu-b2b
  
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: m2c
  description: Meter to Cash.
spec:
  type: product-area
  profile:
    displayName: M2C
    email: m2c@example.com
    picture: https://cdn-icons-png.flaticon.com/512/2037/2037737.png
  parent: eu-b2b

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: epc
  description: EPC.
spec:
  type: product-area
  profile:
    displayName: EPC
    email: epc@example.com
    picture: https://cdn-icons-png.flaticon.com/512/2037/2037737.png
  parent: eu-b2b

---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: dbb-infra
  description: Infra
spec:
  owner: sre
  domain: dbb

---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: dbb-etl
  description: ETLs.
spec:
  owner: m2c
  domain: dbb

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: consumption_es_g_v1
  description: consumption_es_g_v1
spec:
  type: service
  lifecycle: production
  owner: m2c
  system: dbb-etl
