apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: eu-b2b
  description: eu-b2b
spec:
  type: business-unit
  profile:
    displayName: EU B2B
    email: eu-b2b@example.com
    picture: https://cdn-icons-png.flaticon.com/512/2037/2037737.png
  children: [sre, m2c]

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: sre
  description: Site Reliability Engineering.
spec:
  type: business-unit
  profile:
    displayName: Site Reliability Engineering
    email: sre@example.com
    picture: https://cdn-icons-png.flaticon.com/512/2037/2037737.png
  parent: eu-b2b
  
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: m2c
  description: Meter to Cash.
spec:
  type: product-team
  profile:
    displayName: M2C
    email: m2c@example.com
    picture: https://cdn-icons-png.flaticon.com/512/2037/2037737.png
  parent: eu-b2b

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: epc
  description: EPC.
spec:
  type: product-team
  profile:
    displayName: EPC
    email: epc@example.com
    picture: https://cdn-icons-png.flaticon.com/512/2037/2037737.png
  parent: eu-b2b

---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: infra
  description: Infra
spec:
  owner: sre

---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: meter-asset
  description: Meter Asset data
spec:
  owner: m2c
  
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: dbb-infra
  description: Dbb Infra.
spec:
  owner: sre
  domain: infra

---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: m2c-etl
  description: M2C ETL.
spec:
  owner: m2c
  domain: infra

---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: dbb-import-etl
  description: ETL to import data into dbb.
spec:
  owner: artist-relations-team
  domain: artists

---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: dbb-export-etl
  description: ETL to export data from dbb.
spec:
  owner: artist-relations-team
  domain: artists

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: consumption_es_g
  description: consumption_es_g
spec:
  type: etl
  lifecycle: production
  owner: m2c
  system: dbb-import-etl
